### ISSUE TITLE
问题自查

### ISSUE THREAD

**Issue by putyy** [putyy/res-downloader#73]
windows查找问题： 打开PowerShell 将软件拖入进入后回车运行 查看提示是否报错

Mac查找问题： 打开应用程序->找到res-downloader->右键显示包内容->找到Contents/MacOS下的res-downloader文件->拖入终端回车运行  查看提示是否报错

**Comment by chaoweimt** [comment]
正常的，但还是 loading

**Comment by ErickyDF** [comment]
Hi Putty,
使用的macOS 
打开后，持续“loading ...”，
之前在“设置”中设置了代理，目前一直“loading ...”，因此无法修改代理设置，
通过“显示包内容”检查后，发现“setProxyErrorCallback null”，
请问后续如何处理？

**Comment by gvariable** [comment]
在终端中运行包内容中的二进制，显示内容为“”“res-downloader Helper (Renderer)[84682:470832] CoreText note: Client requested name ".PingFangUIDisplaySC-Bold", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].”“”

**Comment by putyy** [comment]
> Hi Putty, 使用的macOS 打开后，持续“loading ...”， 之前在“设置”中设置了代理，目前一直“loading ...”，因此无法修改代理设置， 通过“显示包内容”检查后，发现“setProxyErrorCallback null”， 请问后续如何处理？

软件是2.1.1吗

**Comment by putyy** [comment]
> 在终端中运行包内容中的二进制，显示内容为“”“res-downloader Helper (Renderer)[84682:470832] CoreText note: Client requested name ".PingFangUIDisplaySC-Bold", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].”“”

什么系统？

**Comment by gvariable** [comment]
macOS 15.0
res-downloader 2.1.1

**Comment by putyy** [comment]
> macOS 15.0 res-downloader 2.1.1

刚升级到15.0  我这边正常 你重新安装看看

**Comment by ErickyDF** [comment]
> > Hi Putty, 使用的macOS 打开后，持续“loading ...”， 之前在“设置”中设置了代理，目前一直“loading ...”，因此无法修改代理设置， 通过“显示包内容”检查后，发现“setProxyErrorCallback null”， 请问后续如何处理？
> 
> 软件是2.1.1吗

是的，版本是2.1.1

**Comment by ErickyDF** [comment]
> > > Hi Putty, 使用的macOS 打开后，持续“loading ...”， 之前在“设置”中设置了代理，目前一直“loading ...”，因此无法修改代理设置， 通过“显示包内容”检查后，发现“setProxyErrorCallback null”， 请问后续如何处理？
> > 
> > 
> > 软件是2.1.1吗
> 
> 是的，版本是2.1.1

我是用的系统版本是 macos 10.15.7，res-downloader 2.1.1

**Comment by L-feng-f** [comment]
我是用的系统版本是 macos 13.3.1，res-downloader 2.1.1

终端
➜  ~ /Applications/res-downloader.app/Contents/MacOS/res-downloader
启动 aria2
aria2 成功启动
17:31:43.713 › --------------proxy catch err-------------- Error: invalid value for upstreamProxy: "http://127.0.0.1:7890/"
    at new Proxy (/Applications/res-downloader.app/Contents/Resources/app.asar/node_modules/hoxy/lib/proxy.js:216:15)
    at Object.createServer (/Applications/res-downloader.app/Contents/Resources/app.asar/node_modules/hoxy/lib/main.js:21:12)
    at /Applications/res-downloader.app/Contents/Resources/app.asar/dist-electron/main/index.js:29:15323
    at new Promise (<anonymous>)
    at PY (/Applications/res-downloader.app/Contents/Resources/app.asar/dist-electron/main/index.js:29:15283)
    at /Applications/res-downloader.app/Contents/Resources/app.asar/dist-electron/main/index.js:38:13144
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89595)
    at WebContents.emit (node:events:513:28)

**Comment by putyy** [comment]
> 我是用的系统版本是 macos 13.3.1，res-downloader 2.1.1
> 
> 终端 ➜ ~ /Applications/res-downloader.app/Contents/MacOS/res-downloader 启动 aria2 aria2 成功启动 17:31:43.713 › --------------proxy catch err-------------- Error: invalid value for upstreamProxy: "http://127.0.0.1:7890/" at new Proxy (/Applications/res-downloader.app/Contents/Resources/app.asar/node_modules/hoxy/lib/proxy.js:216:15) at Object.createServer (/Applications/res-downloader.app/Contents/Resources/app.asar/node_modules/hoxy/lib/main.js:21:12) at /Applications/res-downloader.app/Contents/Resources/app.asar/dist-electron/main/index.js:29:15323 at new Promise () at PY (/Applications/res-downloader.app/Contents/Resources/app.asar/dist-electron/main/index.js:29:15283) at /Applications/res-downloader.app/Contents/Resources/app.asar/dist-electron/main/index.js:38:13144 at WebContents. (node:electron/js2c/browser_init:2:89595) at WebContents.emit (node:events:513:28)

软件内代理留空

**Comment by putyy** [comment]
> > > > Hi Putty, 使用的macOS 打开后，持续“loading ...”， 之前在“设置”中设置了代理，目前一直“loading ...”，因此无法修改代理设置， 通过“显示包内容”检查后，发现“setProxyErrorCallback null”， 请问后续如何处理？
> > > 
> > > 
> > > 软件是2.1.1吗
> > 
> > 
> > 是的，版本是2.1.1
> 
> 我是用的系统版本是 macos 10.15.7，res-downloader 2.1.1

卸载重装 软件内代理留空

**Comment by TwilightZPM** [comment]
你好，系统是win11，23H2，软件版本是2.1.3，打开软件后没有网络，重新手动安装证书也没用。PowerShell打开后打开网页报错如下，麻烦帮忙看下吧，感谢
启动 aria2
aria2 成功启动
setProxyErrorCallback Error: connect ETIMEDOUT 2606:4700:3033::6815:325:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '2606:4700:3033::6815:325',
  port: 443
}
setProxyErrorCallback Error: connect ETIMEDOUT 240e:97d:2000:c0e::28:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '240e:97d:2000:c0e::28',
  port: 443
}

**Comment by seadogbest** [comment]
aria2RpcClient err: TypeError: Cannot read properties of undefined (reading 'length')
    at _F.calculateDownloadProgress (D:\wechatdownload\res-downloader\resources\app.asar\dist-electron\main\index.js:22:14458)
    at D:\wechatdownload\res-downloader\resources\app.asar\dist-electron\main\index.js:29:2630
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
    微信视频号解析下载失败 这个是报错日志 辛苦大佬看下

**Comment by seadogbest** [comment]
图片和其他视频都是ok的 就只是微信视频号的视频解析下载失败

**Comment by aini9898wo** [comment]
> windows查找问题: 打开PowerShell将软件拖入进入后回车运行查看提示是否报错
> 
> Mac查找问题: 打开应用程序->找到res-downloader->右键显示包内容->找到内容/MacOS下的res-downloader文件->拖入终端回车运行查看提示是否报错

修改端口和ip地址后打不开软件了，卸载重装也是，重启也打不开，有什么办法吗

**Comment by F-NS** [comment]
微信小程序的视频探测不到

<img width="440" height="828" alt="Image" src="https://github.com/user-attachments/assets/009eb106-ae29-4098-8b14-bf86fca07b66" />

**Comment by zhengqing7319** [comment]
抖音平台视频下载后显示【错误】具体：download failed with 1 errors: task 0 failed after 3 attempts: unexpected status code: 206，下载的视频无法打开。MAC系统

**Comment by putyy** [comment]
> 抖音平台视频下载后显示【错误】具体：download failed with 1 errors: task 0 failed after 3 attempts: unexpected status code: 206，下载的视频无法打开。MAC系统

安装v4版本
