### ISSUE TITLE
MAC提示下载失败

### ISSUE THREAD

**Issue by hahafeixiu** [putyy/res-downloader#99]
mac：Sonoma 14.6.1
公众号视频，点击下载，提示下载失败；但实际文件下载成功；后台错误信息：
TypeError: Cannot read properties of undefined (reading 'length')
    at Aria2RPC.calculateDownloadProgress (/xxxx/res-downloader/electron/main/aria2Rpc.ts:40:38)
    at /xxxx/res-downloader/electron/main/ipc.ts:117:61
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

求大神指点~~！！

**Comment by putyy** [comment]
> Cannot read properties of undefined (re

下载进度计算有点问题 不管他就行
